/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) throws FileNotFoundException {

        try {
            Gson gson = new Gson();

            //originally used scanner; was not working.
            //Scanner scanQuotes = new Scanner(new File ("/src/main/resources/quotes.json"));

            Reader quoteReader = Files.newBufferedReader(Paths.get("quotes/src/main/resources/quotes.json"));

            Quote[] quoteArray = gson.fromJson(quoteReader, Quote[].class);

            int randomizer = (int)(Math.random() * quoteArray.length);
            System.out.println(quoteArray[randomizer]);

            quoteReader.close();

        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
        class ItemDTO {
            String author;
            String quoteBody;
        }
        class TypeDTO {
            String author;
            String quoteBody;
        }
    }


